name: teslo_shop
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  dio: ^5.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  go_router: ^16.3.0
  google_fonts: ^6.3.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/loaders/
    - assets/images/
    - google_fonts/montserrat_alternates/
